/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/book.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/book.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 156.31, 29.064]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.pagina} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.capa} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.interior} />
      </group>
    </group>
  )
}

useGLTF.preload('/book.gltf')
